apiVersion: v1
kind: Service
metadata:
  name: java-api
  namespace: default  # Make sure the namespace matches the deployment
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: java-app
  type: ClusterIP  # Internal communication
